railtour/urls.py
from django.urls import path
from . import views

app_name = 'railtour'
urlpatterns = [
    path("",views.trasy, name='trasy'),
    path('stanice', views.stanice, name='stanice'),
    path('spojeni', views.spojeni, name='spojeni'),
    path('odjezdy', views.odjezdy, name='odjezdy'),
]

rt/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('railtour/', include("railtour.urls")),
    path('ajax/', include("railtour.ajax_urls")),
    path('', lambda request: redirect('railtour/', permanent=True))
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=0.5">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" type="text/css" href="{% static 'railtour.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <title>{% block title %}Railtour{% endblock title %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
        <script src="{% static 'railtour/railtour.js' %}" type="text/javascript"></script>
        {% block javascript %}{% endblock javascript %}
</head>
<body>
    {% include 'menu.html' %}
    {% block content %}{% endblock content %}
</body>
</html>

templates/menu.html
<header>
    <nav class="navbar fixed-top navbar-expand-sm bg-info navbar-dark">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'railtour:stanice' %}">Editor stanic</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'railtour:spojeni' %}">Vyhledat spojení</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'railtour:odjezdy' %}">Odjezdy/příjezdy</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'railtour:trasy' %}">Výpočet tras</a></li>
            </ul>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ml-auto"><a class="nav-link" href='railtour/logout'>Odhlásit</a></li>
            </ul>
        </div>
        <hr>
    </nav>
</header>